source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5", ask=FALSE)
install.packages('devtools', repos="https://cran.itam.mx")
install.packages('ggplot2', repos="https://cran.itam.mx")
install.packages('dplyr', repos="https://cran.itam.mx")
install.packages('data.table', repos="https://cran.itam.mx")
install.packages('tidyr', repos="https://cran.itam.mx")
install.packages('reshape2', repos="https://cran.itam.mx")
install.packages('lazyeval', repos="https://cran.itam.mx")
install.packages('matrixStats', repos="https://cran.itam.mx")
install.packages('shiny', repos="https://cran.itam.mx")
options(download.file.method = "wininet")
devtools::install_github("pachterlab/sleuth")